WITH PARAMS AS (
    SELECT
        CAB.CODEMP,
        CAB.CODPARC,
        CASE WHEN CAB.CODTIPOPER = 1057 THEN 1 ELSE 0 END AS IS_TOP1057
    FROM TGFCAB CAB
    WHERE CAB.NUNOTA = 23140
),
LISTA_PRODUTOS AS (
    SELECT 12141 AS CODPROD, 0 AS ORDEMHIERARQUIA FROM DUAL
    UNION
    SELECT PAI.CODPRODALT AS CODPROD, 1 AS ORDEMHIERARQUIA
    FROM TGFPAL PAI
    WHERE PAI.CODPROD = 12141
    UNION
    SELECT FILHO.CODPROD AS CODPROD, 1 AS ORDEMHIERARQUIA
    FROM TGFPAL FILHO
    WHERE FILHO.CODPRODALT = 12141
    UNION
    SELECT PAI.CODPRODALT AS CODPROD, 2 AS ORDEMHIERARQUIA
    FROM TGFPAL FILHO
    JOIN TGFPAL PAI ON FILHO.CODPROD = PAI.CODPROD
    WHERE FILHO.CODPRODALT = 12141
      AND PAI.CODPRODALT <> 12141
)
SELECT * FROM (
    SELECT
        LP.ORDEMHIERARQUIA,
        PRO.CODPROD,
        PRO.REFERENCIA,
        PRO.DESCRPROD,
        PRO.MARCA,
        PRO.AD_COMERCIALIZA AS COMERCIALIZA,
        PRO.CODGRUPOPROD,
        GRU.DESCRGRUPOPROD,
        PER.CODGRUMARKUP,
        GRUMKP.DESCRGRUMARKUP,
        PER.PRIORIDADE,
        PMK.CODMARKUP,
        (NVL(CUS.CUSGER, 0) * (1 - NVL(DES.PERCENTUAL, 0) / 100.0)) / NULLIF(1 - ((NVL(PMK.PERCMARKUP, 0) + NVL((SELECT SUM(PERCDESP) FROM AD_DESPOPER WHERE ATIVO = 'S' AND CODEMP = PARAMS.CODEMP), 0)) / 100.0), 0) AS PRECO_CALCULADO,
        NVL(DES.PERCENTUAL, 0) AS PERCDESC,
        NVL(EST.ESTOQUE, 0) AS ESTOQUE,
        NVL(EST.ESTOQUE, 0) - NVL(EST.RESERVADO, 0) AS SALDO,
        NVL(EST.RESERVADO, 0) AS RESERVADO,
        COALESCE((SELECT SUM(I.QTDNEG) FROM TGFITE I JOIN TGFCAB C ON I.NUNOTA = C.NUNOTA WHERE I.CODPROD = PRO.CODPROD AND I.PENDENTE = 'S' AND C.TIPMOV = 'O' AND C.STATUSNOTA = 'L'), 0) AS COMPRAPENDENTE,
        (SELECT TO_CHAR(MIN(ITE2.AD_DTPREVENTGER), 'DD/MM/YYYY') FROM TGFITE ITE2 JOIN TGFCAB CAB2 ON CAB2.NUNOTA = ITE2.NUNOTA WHERE ITE2.CODPROD = PRO.CODPROD AND ITE2.CODEMP = PARAMS.CODEMP AND CAB2.STATUSNOTA = 'L' AND CAB2.PENDENTE = 'S' AND ITE2.AD_DTPREVENTGER IS NOT NULL) AS DTPROXENTREGA,
        (SELECT MAX(ITE.VLRUNIT) FROM TGFCAB CAB JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA WHERE ITE.CODPROD = PRO.CODPROD AND CAB.CODPARC = PARAMS.CODPARC AND CAB.CODTIPOPER = 1000 AND CAB.STATUSNOTA = 'L' AND CAB.DTMOV = (SELECT MAX(DTMOV) FROM TGFCAB WHERE CODTIPOPER = 1000 AND STATUSNOTA = 'L')) AS VLRULTIMACOTACAO,
        (SELECT MAX(ITE.VLRUNIT) FROM TGFCAB CAB JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA WHERE ITE.CODPROD = PRO.CODPROD AND CAB.CODPARC = PARAMS.CODPARC AND CAB.TIPMOV = 'V' AND CAB.STATUSNOTA = 'L' AND CAB.DTMOV = (SELECT MAX(DTMOV) FROM TGFCAB WHERE CAB.TIPMOV = 'V' AND STATUSNOTA = 'L')) AS VLRULTIMAVENDA
    FROM LISTA_PRODUTOS LP
    CROSS JOIN PARAMS
    JOIN TGFPRO PRO ON LP.CODPROD = PRO.CODPROD
    JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
    LEFT JOIN AD_PERFPRODMKP PER ON (
        PER.ROWID = (
            SELECT P2.ROWID FROM AD_PERFPRODMKP P2
            WHERE (P2.CODPROD = PRO.CODPROD OR P2.CODPROD IS NULL)
                AND (P2.CODGRUPOPROD = PRO.CODGRUPOPROD OR P2.CODGRUPOPROD IS NULL)
                AND (P2.CODMARCA = PRO.CODMARCA OR P2.CODMARCA IS NULL)
                AND (P2.CODPARCFORN = PRO.CODPARCFORN OR P2.CODPARCFORN IS NULL)
                AND (P2.CODEMP = PARAMS.CODEMP OR P2.CODEMP IS NULL)
                AND P2.PRIORIDADE = (
                    SELECT MAX(P3.PRIORIDADE) FROM AD_PERFPRODMKP P3
                    WHERE (P3.CODPROD = PRO.CODPROD OR P3.CODPROD IS NULL)
                        AND (P3.CODGRUPOPROD = PRO.CODGRUPOPROD OR P3.CODGRUPOPROD IS NULL)
                        AND (P3.CODMARCA = PRO.CODMARCA OR P3.CODMARCA IS NULL)
                        AND (P3.CODPARCFORN = PRO.CODPARCFORN OR P3.CODPARCFORN IS NULL)
                        AND (P3.CODEMP = PARAMS.CODEMP OR P3.CODEMP IS NULL)
                )
            ORDER BY
                CASE WHEN P2.CODPROD = PRO.CODPROD THEN 1 ELSE 0 END DESC,
                CASE WHEN P2.CODGRUPOPROD = PRO.CODGRUPOPROD THEN 1 ELSE 0 END DESC,
                CASE WHEN P2.CODMARCA = PRO.CODMARCA THEN 1 ELSE 0 END DESC,
                CASE WHEN P2.CODPARCFORN = PRO.CODPARCFORN THEN 1 ELSE 0 END DESC
            FETCH FIRST 1 ROW ONLY
        )
    )
    LEFT JOIN AD_PERMARKUP PMK ON PMK.CODGRUMARKUP = PER.CODGRUMARKUP AND PMK.CODMARKUP <= 5
    LEFT JOIN AD_GRUMARKUP GRUMKP ON PER.CODGRUMARKUP = GRUMKP.CODGRUMARKUP
    LEFT JOIN TGFCUS CUS ON CUS.CODPROD = PRO.CODPROD
        AND (CUS.CODEMP = PARAMS.CODEMP OR PARAMS.CODEMP IS NULL)
        AND CUS.DTATUAL = (SELECT MAX(DTATUAL) FROM TGFCUS WHERE CODPROD = PRO.CODPROD AND CODEMP = PARAMS.CODEMP)
    LEFT JOIN TGFDES DES ON (
        DES.ROWID = (
            SELECT D2.ROWID FROM TGFDES D2
            WHERE (D2.CODEMP = PARAMS.CODEMP OR D2.CODEMP = 0)
                AND (D2.CODPARC = PARAMS.CODPARC OR D2.CODPARC = 0)
                AND D2.CODPROD = PRO.CODPROD
                AND D2.DTINICIAL <= SYSDATE AND D2.DTFINAL >= SYSDATE
            ORDER BY D2.DTFINAL DESC
            FETCH FIRST 1 ROW ONLY
        )
    )
    LEFT JOIN TGFEST EST ON PRO.CODPROD = EST.CODPROD AND EST.CODEMP = PARAMS.CODEMP
        AND ((PARAMS.IS_TOP1057 = 1 AND EST.CODLOCAL = 201) OR (PARAMS.IS_TOP1057 = 0 AND EST.CODLOCAL = 101))
        AND EST.CODPARC = 0
)
PIVOT (
    MAX(PRECO_CALCULADO)
    FOR CODMARKUP IN (1 AS FAIXA1, 2 AS FAIXA2, 3 AS FAIXA3, 4 AS FAIXA4, 5 AS FAIXA5)
)
ORDER BY ORDEMHIERARQUIA ASC, CODPROD ASC
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
